### ISSUE TITLE
It's possible to get stuck falling

### ISSUE THREAD

**Issue by janhohenheim** [idanarye/bevy-tnua#2]
![image](https://user-images.githubusercontent.com/9047632/226189399-70a57d6c-c141-4bcc-8353-c42c42d8c97c.png)
Repro steps: 
- go to the right of the solver groups text
- jump
- move left into the text while jumping

While holding left, the character will be stuck in the air doing their falling animation in place.

**Comment by idanarye** [comment]
So, the actual problem here is that Tnua casts a ray to judge the proximity to the ground. When you are on the edge, the ray does not it the obstacle but the collider does.

One way to fix this is by casting a shape instead of a ray. The example allows it with the _Sensor Shape_ option:
![image](https://user-images.githubusercontent.com/1149255/226208513-a36df9bb-911b-4814-b158-33c3ec15f60e.png)

I'm not sure if this needs to be enforced though, or just better documented.

**Comment by janhohenheim** [comment]
Better documentation seems like the right approach to me, the raycast should surely suffice for many users
