### ISSUE TITLE
Something causes the character to float up

### ISSUE THREAD

**Issue by janhohenheim** [idanarye/bevy-tnua#3]
![image](https://user-images.githubusercontent.com/9047632/226189630-52022a62-4edc-4a74-a969-158638fb4de0.png)

Right after reporting #2, I tabbed back into the 3D platforming example and found the character wayyyy up in the sky. It took them a while to fall down to the ground.
I don't know if this is a consequence of #2, caused by the general lag of me having other stuff open on my computer at the same time, the tabbing out or the waiting.

Repro steps:

- Reproduce #2 
- Tab out for a couple of mins
- Compile something to make your CPU occupied (idk if this step is necessary)
- Tab back in

**Comment by idanarye** [comment]
This is the problem:
```rust
let dampening_force = relative_velocity * config.spring_dampening;
```
The dampening force is linear with the velocity, but it's an acceleration rather than a velocity so if a frame is long its effects are drastic. I'll have to multiply it by the frame duration - which means that `spring_dampening` will have to be re-calibrated, making this a breaking change.

**Comment by janhohenheim** [comment]
Wow, good job on finding the problem this quickly! :)
