### ISSUE TITLE
Use git tags to tag published cargo versions

### ISSUE THREAD

**Issue by msvbg** [idanarye/bevy-tnua#49]
It's helpful to be able to see which version of the source code corresponds to which version published on crates.io, so it would be great if the git repo were tagged accordingly. It may also make sense to use the same version number for all crates given that this is a monorepo of sorts.

**Comment by idanarye** [comment]
It's a monorepo, but the crates get updated individually. If I force them all to use the same version there will be version gaps.

**Comment by rltvty** [comment]
you could do `crate-version` tagging. example: `bevy-tnua-v0.20.0`

I agree that it would be super helpful to be able to see the code that corresponds to versions of published crates.

**Comment by idanarye** [comment]
Good idea, @rltvty - though I'm thinking of dropping the `bevy-tnua` prefix - so the main crate will just be `v0.20.0`, but the other crates will be e.g. `physics-integration-layer-v0.4.0` instead of `bevy-tnua-physics-integration-layer-v0.4.0` (which is way too long...). Other than length considerations, I don't want to create the impression that the crate name is contained as is in the tag because the actual physics backend integration crates will be sharing their tags - e.g. both `bevy-tnua-rapier2d` and `bevy-tnua-rapier3d` will use the `avian-v0.7.0` tag.

I can spend a few hours to do it manually, or a few days to do automate it. Of course I'll choose the latter. In fact, I've already started to work on it: https://github.com/idanarye/retrospective-crate-version-tagging.

**Comment by idanarye** [comment]
Can't run my tool before this is solved: https://github.com/cli/cli/issues/9773 (I tried, and some of the releases don't work)
