### ISSUE TITLE
Support floating shape cast

### ISSUE THREAD

**Issue by erictuvesson** [idanarye/bevy-tnua#51]
Currently the floating ray cast is not a shape cast, it would be nice to be able to change it to shape cast to avoid issues like this where the character gets stuck on the edge.

![image](https://github.com/idanarye/bevy-tnua/assets/1263211/c3384cf2-987f-45a0-8305-6347852fa035)

**Comment by idanarye** [comment]
This is already supported. Since the shape is defined as a collider of the physics backend, the component that adds this options is in the physics integration crate and not in the main crate. It is usually called `Tnua<physics-backend>SensorShape`. For example, if you are using XPBD 2D, you need [`TnuaXpbd2dSensorShape`](https://idanarye.github.io/bevy-tnua/bevy_tnua_xpbd2d/struct.TnuaXpbd2dSensorShape.html).

**Comment by erictuvesson** [comment]
Awesome, thanks works like a charm!
