### ISSUE TITLE
Seeing massive lag due to update_proximity_sensors_system i think 

### ISSUE THREAD

**Issue by ethereumdegen** [idanarye/bevy-tnua#67]
I am using TNUA with avian3d and i am getting massive lag and it seems to be from this: 

![image](https://github.com/user-attachments/assets/51c282fb-d28e-4d07-ab41-318d08bd1975)

what could this mean  ?

**Comment by idanarye** [comment]
`update_proximity_sensors_system`, in its most basic form, does a simple raycast and queries some components of the entity it hits. I'm not sure why it's taking so long (a raycast should be relatively quick, shouldn't it?), but it also does some other things that you may or may not be able to disable:

1. If you use `TnuaAvian3dSensorShape` it does a shapecast instead, which it a bit more complex. If you use it - can you try disabling it (simply don't add that component)?
2. If you use `TnuaGhostSensor` and have ghost sensors, the raycast would have to go through all of them. Maybe you have too many? Can you disable it and see how it affects performance?
3. As a fix for #14, `update_proximity_sensors_system` also checks for collision between the character and the entity it hits. This is data that's already computed, but it does loop through all the [contact manifolds](https://docs.rs/avian3d/0.1.2/avian3d/collision/struct.Contacts.html#structfield.manifolds), so if you have too many of them it could take some time. This one is harder to disable - you'd have to comment it out locally (or, if you need help, I can make a branch for you) - so let's check the other things out first?

**Comment by ethereumdegen** [comment]
Thanks for the quick reply! 
  I have no ghost sensors.  However I am using the sensor shape:

 tnua_sensor_shape: TnuaAvian3dSensorShape(Collider::capsule(
              
                radius * 1.0,
                  height * 0.95,
            )),



its okay to just not add it at all ? OK I still have this on my character 

  collider: Collider::capsule(radius, height),
  
 I removed the tnua sensorshape and my character can no longer move around BUT the lag is all gone! my FPS shot up from 25 to 60.  So what does that mean?   I cant just not have the tnua sensorshape...right?  It seems like my character doesnt work without it they cant walk around and keep doing the jump animation in  place.   
  
 .

**Comment by ethereumdegen** [comment]
Also it seems if i change the TnuaAvian3dSensorShape to use a cylinder instead of a capsule, my fps goes from 25 to 40, but still doesnt go up to 60.. the only way i can get 60 if is i remove the sensorshape completely.   I have a 'normal' amount of physics objects in my scene: about 400 physics doodads and 80 terrain meshes but the vast majority of them are nowhere near the player.

**Comment by idanarye** [comment]
Maybe I should add a strong emphasis about this to the docs (or a "pitfalls" section in the readme?) but... sensor shapes should generally be flat. And unless you have a good reason to deviate from it - a zero-height cylinder for 3D and zero-height rectangle (or cuboid, if you're using Rapier) for 2D. So before you give up on a sensor-shape - try changing it to a zero-height cylinder. It's a simpler shape than a capsule, and there's a good chance it'll solve your performance issues.

It won't solve your new issue though:

> I removed the tnua sensorshape and my character can no longer move around

The reason this happens is that when you moved from a capsule-cast to a raycast you've lost the height of the capsule - which I suspect brings your character's actual collider to not float above the ground. It's actually worse - since Tnua _thinks_ it floats too high above the ground, it applies a strong downward force to get it to the configured `float_height` - which probably causes great friction which prevents your character from moving.

Since a zero-height cylinder also has no height, the problem will remain (though it's possible that if you keep the height and just switch from a capsule to a cylinder it'll solve the performance issues because a cylinder is a simpler shape and it's flat caps have more simple contacts with the ground than the capsule's round caps)

The proper way to solve it is to add the lost height to the `float_height`. Your capsule's height is `height * 0.95`, but only half of it (from the projected capsule's center down) was being "added" to the `float_height` - so try increasing it by `height * 0.475`. Then again - the docs say that the capsule height is "excluding the hemispheres", so maybe you'd need more than that.

**Comment by ethereumdegen** [comment]
Yay! okay you were right.  I increased my float height by about 0.5 and now i can walk around without the TnuaSensorShape and now its super snappy there is no lag at all.   

My one issue is that it seems like I can clip through small bumps / hills in my terrain now but that could be due to the terrain colliders but also it actually improved my collision with terrain walls- i can no longer 'climp' up vertical cliffs like i could with the capsule sensor shape so that is actually a good thing.  this is good for now.  My only problem now is my character model is halfway into the floor due to the change to the float height -- should i just compensate for this by offsetting the model gltf scene? or is there a better way.  thanks

**Comment by idanarye** [comment]
> Also it seems if i change the TnuaAvian3dSensorShape to use a cylinder instead of a capsule, my fps goes from 25 to 40, but still doesnt go up to 60.

Is that with a flat cylinder, or with a cylinder with the same height the capsule was? If it's the latter, can you change it to a flat cylinder (with the amended `float_height`) and see it affects your performance? I think you need a shapecast to solve your "clip through small bumps / hills" problem, And while I'm not very familiar with the specifics of how Avian handles shapecasts, I suspect a flat shape (when the flatness is in the cast direction) should be more performant than a shape with a volume.

> i can no longer 'climb' up verticalish cliffs like i could with the capsule sensor shape so that is actually a good thing.

Depending on the cliff, this may be solvable by making the cast shape a little smaller than the collider (I'm talking about it's section cut parallel to the ground. The height of the cast shape should be zero, which obviously makes its volume smaller than the collider)

But you should also look at [the `max_slope` field](https://docs.rs/bevy-tnua/0.20.0/bevy_tnua/builtins/struct.TnuaBuiltinWalk.html#structfield.max_slope).

> My only problem now is my character model is halfway into the floor due to the change to the float height -- should i just compensate for this by offsetting the model gltf scene? or is there a better way. thanks

Increase the float height some more, until the model's feet touch the ground.

**Comment by ethereumdegen** [comment]
I tried a shapecast of a cylinder with zero height and it wasnt as laggy but still pretty laggy - much more so then i would expect /hope.  I feel like its doing way more work than it needs to... ?  

Also the more i increase the float height, the LOWER my character model sinks into the ground .. ?  This is confirmed.  I dont get it.

**Comment by idanarye** [comment]
Just for science - try using the simplest shape, [`Collider::triangle`](https://docs.rs/avian3d/0.1.2/avian3d/collision/collider/struct.Collider.html#method.triangle), and see how it affects the performance?

**Comment by ethereumdegen** [comment]
Okay i will try that.  Oh another quick feedback/question.  Now it seems like my character has a hard time going up stairs. Is there a way i can add a "max step up" height so if a step is only say 0.3 units tall the character can just step right up it ?  Or would i need to build that myself somehow ?

**Comment by idanarye** [comment]
The floating capsule model does not need special handling of stairs. The idea is that the collider does not collide with the steps - it floats above them - and when it finds itself above a stair it suddenly determines that it floats too low and adjusts accordingly.

If it doesn't work for you, I can think of two things you should be looking into:

1. Is your collider not floating high enough? Since you've moved from a shapecast to a raycast, the cast can no longer detect the stairs when they merely enter the character's "shadow" (assume a shadow cast by a directly-downward directional light) - the character's center must be above the stair in order for the ray to hit it. This can cause two problems:
    * Since your collider is a capsule, it has less room for the stair to fit in the closer it gets to the center. Maybe the edge of the cap floats high enough for the stair but the center of it doesn't.
    * How wide is each stair? It's possible that the character cannot position itself so that the ray would hit the first stair because the collider already hits the second stair.

    Either way, try to increase the float height and/or decrease the collider height so that the character will float higher and see if it fixes things.
2. Is the character able to climb stairs, but when it moves too fast it does not climb them fast enough and "stumbles" on them? In that case, try increasing the [`spring_strengh`](https://docs.rs/bevy-tnua/0.20.0/bevy_tnua/builtins/struct.TnuaBuiltinWalk.html#structfield.spring_strengh).

**Comment by ethereumdegen** [comment]
Ohhhh right of course okay I just increased my float height and now my walking with stairs works perfectly. Yes that makes more sense thanks.
