### ISSUE TITLE
Float height seems to be not working in 0.15 

### ISSUE THREAD

**Issue by ethereumdegen** [idanarye/bevy-tnua#73]
So I upgraded to 0.15, using avian and tnua,  and it seems like float height on TnuaBuiltInWalk has no effect.  I say this because my character is clipping into the ground and constantly playing the jump animation and cannot move.  Similar to like if my float height is too small.  So i hacked in a gigantic value for float height, like 9.0, and it behaves the same. 

what can i try ?  whats going on here

**Comment by idanarye** [comment]
This is due to a change in Avian itself - they changed the default collision layers (the ones you get when you don't explicitly add `CollisionLayers`) from `ALL` to `default()`. This means that if the character does that does not include the default and the ground does not have the `CollisionLayers` component at all (or vice versa) - they won't collide with each other. Tnua simply respect that.

If it was just an issue in Tnua, the character wouldn't be clipping into the ground - it'd just be laying on it without floating.

**Comment by ethereumdegen** [comment]
okay so the character collider seems to be hitting the ground but the TNUA sensor is not seeing the ground  ? that kind of makes sense.  But why is my character able to collide  w the ground and not the TNUA sensor ?

**Comment by ethereumdegen** [comment]
I found out something very weird.  I patched bevy-tnua with a  local repo clone and put a print statement in the system update_proximity_sensors_system 

the print statement never prints......

**Comment by ethereumdegen** [comment]
yikes that was the issue... ugh so confusing
